Obmin 295 creating an input with formik field logic
Wolshebnik/Obminyashka-components pull request #11
Opened 2023-02-20 11:01 UTC by ASGladchenko

- fixed styles in show-password image centering without variable scrolling
- change structure of Input for same reason 
- create an "InputField" component, for the input to work with the Formik logic( wrapper with logic)
- connected yup library 
- connected InputField in components/index

2023-02-20 21:05 UTC, Wolshebnik requested changes

2023-02-20 21:05 UTC, Wolshebnik commented on src/components/input-field/index.tsx
> +      {({ field: { value, onChange, ...props }, meta, form }: fieldProps) => {
correct name is fieldProps

2023-02-20 21:05 UTC, Wolshebnik commented on src/components/input-field/index.tsx
> +            {...props}
fieldProps must be first
and props must be last

2023-02-20 21:05 UTC, Wolshebnik commented on src/components/input-field/types.ts
> +  error?: string;
sort

2023-02-20 21:58 UTC, Wolshebnik requested changes

2023-02-20 21:58 UTC, Wolshebnik commented on src/components/input/styles.ts
>      width: 24px;
And I guess You forgot to export your component from storybook
components/index.ts

2023-02-21 17:03 UTC, Kyslytsia approved these changes

2023-02-21 17:20 UTC, Mish-hash approved these changes

2023-02-22 12:17 UTC, Wolshebnik approved these changes

2023-02-22 12:48 UTC, merged