Obmin 297 created toast
Wolshebnik/Obminyashka-components pull request #14
Opened 2023-02-20 20:14 UTC by Kyslytsia

2023-02-20 20:44 UTC, Wolshebnik approved these changes

2023-02-20 20:52 UTC, Voloshkina approved these changes

2023-02-20 21:28 UTC, AkintsevaElizaveta approved these changes

2023-02-20 21:44 UTC, ASGladchenko approved these changes

2023-02-20 21:53 UTC, Wolshebnik requested changes

2023-02-20 21:53 UTC, Wolshebnik commented on src/components/toast/show-message.tsx
> +import { ToastContainerProps } from 'react-toastify';
2 import from one place
it is strange

2023-02-21 10:06 UTC, Wolshebnik requested changes

2023-02-21 10:06 UTC, Wolshebnik commented on src/components/toast/index.tsx
> +import { ToastContainerProps } from 'react-toastify';
Strange imports

2023-02-21 10:12 UTC, Wolshebnik requested changes

2023-02-21 10:12 UTC, Wolshebnik commented on src/components/toast/index.tsx
> +import { ToastContainer, ToastContainerProps } from 'react-toastify';
space

2023-02-21 14:38 UTC, Viktoria-Serkiz approved these changes

2023-02-21 20:50 UTC, Wolshebnik approved these changes

2023-02-21 20:50 UTC, merged