[OBMIN-269] Pagination component
Wolshebnik/Obminyashka-components pull request #15
Opened 2023-02-20 22:08 UTC by cloudmenson

2023-02-20 22:29 UTC, Wolshebnik requested changes

2023-02-20 22:29 UTC, Wolshebnik commented on src/components/page-pagination/styles.ts
> +      border: 1px solid ${theme.colors.btnBlue};
when we have two callbacks or more, we make one callback 
Do you remember?

2023-02-20 22:29 UTC, Wolshebnik commented on src/components/page-pagination/types.ts
> +  prevIcon: ReactNode;
sort

2023-02-20 22:31 UTC, Wolshebnik requested changes

2023-02-20 22:31 UTC, Wolshebnik commented on src/components/page-pagination/Pagination.stories.tsx
> +    </>
Are you sure, what you need fragment?

2023-02-21 16:53 UTC, ASGladchenko approved these changes

2023-02-23 15:54 UTC, Voloshkina approved these changes

2023-02-23 16:01 UTC, Mish-hash approved these changes

2023-02-23 16:22 UTC, Kyslytsia approved these changes

2023-02-23 16:23 UTC, Viktoria-Serkiz approved these changes

2023-02-23 16:25 UTC, Wolshebnik approved these changes

2023-02-23 16:51 UTC, ASGladchenko approved these changes

2023-02-23 18:05 UTC, merged