Obmib 322 create product owner data
Wolshebnik/Obminyashka-components pull request #22
Opened 2023-02-26 19:35 UTC by Kyslytsia

Create ProductOwnerData

2023-02-26 20:01 UTC, Voloshkina commented on src/components/product-owner-data/index.tsx
> +}: IProductOwnerDataProps) => {
sort pls

2023-02-26 20:05 UTC, Voloshkina commented on src/components/product-owner-data/arg-types.ts
> +  translatedText: {
maybe you don't need translatedText?

2023-02-26 20:07 UTC, Voloshkina commented on src/components/product-owner-data/index.tsx
> +  city,
sort pls

2023-02-26 21:53 UTC, Wolshebnik requested changes

2023-02-26 21:53 UTC, Wolshebnik commented on src/components/product-owner-data/index.tsx
> +              <Styles.PostReqDataText style={{ color: 'black' }}>
you need to use color from theme

2023-02-26 21:53 UTC, Wolshebnik commented on src/components/product-owner-data/index.tsx
> +            <Styles.PostReqDataText style={{ width: '200px', color: 'black' }}>
the same

2023-02-26 21:53 UTC, Wolshebnik commented on src/components/product-owner-data/styles.ts
> +  background-color: #fdfcff;
use background color from theme

2023-02-26 21:53 UTC, Wolshebnik commented on src/components/product-owner-data/styles.ts
> +  color: #8f8f8f;
color from theme

2023-02-26 21:53 UTC, Wolshebnik commented on src/components/product-owner-data/index.tsx
> +              <Styles.PostReqDataText style={{ color: 'black' }}>
the same

2023-02-27 12:53 UTC, Voloshkina approved these changes

2023-02-27 13:10 UTC, ASGladchenko approved these changes

2023-02-27 15:23 UTC, Wolshebnik requested changes

2023-02-27 15:23 UTC, Wolshebnik commented on src/components/product-owner-data/styles.ts
> +  font-family: 'Roboto', sans-serif;
Roboto is the default font
check pls
if true remove

2023-02-27 15:23 UTC, Wolshebnik commented on src/components/product-owner-data/types.ts
> +  avatar: string;
avatar should be optional

2023-02-27 15:23 UTC, Wolshebnik commented on src/config/theme/colors.ts
> +  ownerDataBG: magnolia,
name choice is weird
just bg

2023-02-27 15:23 UTC, Wolshebnik commented on src/config/theme/colors.ts
> +  ownerDataText: grey,
name choice is weird
just text

2023-02-27 15:23 UTC, Wolshebnik commented on src/components/product-owner-data/styles.ts
> +  font-family: 'Roboto', sans-serif;
Roboto is the default font
check pls
if true remove

2023-02-27 21:28 UTC, Viktoria-Serkiz approved these changes

2023-02-28 11:10 UTC, cloudmenson commented on src/components/product-owner-data/styles.ts
> +  padding-bottom: 15px;
The background-color property must be lower than the padding

2023-02-28 11:10 UTC, cloudmenson commented on src/components/index.tsx
> +export {ProductOwnerData} from './product-owner-data'
Use prettier: { ProductOwnerData }

2023-02-28 14:40 UTC, AkintsevaElizaveta approved these changes

2023-02-28 19:40 UTC, ASGladchenko approved these changes

2023-02-28 20:04 UTC, merged