[OBMIN-321] description component
Wolshebnik/Obminyashka-components pull request #27
Opened 2023-02-28 14:49 UTC by AkintsevaElizaveta

Transferred description component to Storybook.

2023-02-28 14:51 UTC, Kyslytsia approved these changes

2023-02-28 15:02 UTC, Voloshkina approved these changes

2023-02-28 15:55 UTC, Mish-hash approved these changes

2023-02-28 19:40 UTC, ASGladchenko approved these changes

2023-03-01 08:39 UTC, Viktoria-Serkiz approved these changes

2023-03-01 22:53 UTC, Wolshebnik requested changes
fix conflict
and resolve comment

2023-03-03 08:30 UTC, cloudmenson approved these changes

2023-03-03 09:06 UTC, Wolshebnik approved these changes

2023-03-03 19:59 UTC, merged