[OBMIN-317] helpChildren component
Wolshebnik/Obminyashka-components pull request #28
Opened 2023-03-01 19:52 UTC by cloudmenson

2023-03-01 19:57 UTC, ASGladchenko approved these changes

2023-03-01 20:01 UTC, Viktoria-Serkiz approved these changes

2023-03-01 20:02 UTC, AkintsevaElizaveta approved these changes

2023-03-01 20:59 UTC, Kyslytsia approved these changes

2023-03-01 21:01 UTC, Mish-hash approved these changes

2023-03-01 21:48 UTC, Voloshkina approved these changes

2023-03-01 22:54 UTC, Wolshebnik requested changes
fix conflicts

2023-03-02 13:31 UTC, Wolshebnik requested changes

2023-03-02 13:31 UTC, Wolshebnik commented on src/components/help-children/index.tsx
> +import { Button } from 'components/button';
relative path and sort

2023-03-02 13:31 UTC, Wolshebnik commented on src/config/theme/colors.ts
> +  shadow: shadow,
shadow: shadow => shadow

2023-03-02 17:38 UTC, Wolshebnik approved these changes

2023-03-02 18:07 UTC, merged