Obmin 326 create reset all button
Wolshebnik/Obminyashka-components pull request #34
Opened 2023-03-07 09:19 UTC by Kyslytsia

Create ResetAllButton

2023-03-07 19:51 UTC, Wolshebnik requested changes
wrong logic

2023-03-07 19:56 UTC, Wolshebnik requested changes

2023-03-07 19:56 UTC, Wolshebnik commented on package.json
> +    "react-redux": "^8.0.5",
If you connect redux 
where do you use it?

2023-03-07 19:56 UTC, Wolshebnik commented on package.json
> +    "redux-toolkit": "^1.1.2",
the same

2023-03-07 19:56 UTC, Wolshebnik commented on src/components/reset-all-button/ResetAllButton.stories.tsx
> +// };
why do you want commented code pushed in the main?

2023-03-07 19:56 UTC, Wolshebnik commented on src/components/reset-all-button/index.tsx
> +  getText = 'Cancel Everything',
why so many props?
and why not sorted?

2023-03-07 19:56 UTC, Wolshebnik commented on src/components/reset-all-button/index.tsx
> +  };
Why so many set?

2023-03-16 17:52 UTC, cloudmenson commented on src/components/cancel-everything/CancelEverything.stories.tsx
> +  argTypes: { ...argTypes, onClick: { action: 'onClick' } },
Get it out of here onClick: { action: 'onClick' }, describe it in argTypes

2023-03-17 11:19 UTC, Viktoria-Serkiz approved these changes

2023-03-17 12:02 UTC, cloudmenson approved these changes

2023-03-17 12:02 UTC, cloudmenson commented on src/components/cancel-everything/index.tsx
> +import * as Styles from './styles';
sort pls

2023-03-17 12:12 UTC, Voloshkina approved these changes

2023-03-17 13:08 UTC, merged